-- A instrucao MERGE abaixo faz um INSERT ou UPDATE na tabela HR.EMP2, a partir de dados da tabela HR.EMP3
MERGE INTO HR.EMP2 E2
USING ( SELECT  *
        FROM    HR.EMP3) E3
   ON  (E2.EMPLOYEE_ID = E3.EMPLOYEE_ID)
WHEN  MATCHED THEN  
   UPDATE  
   SET     E2.FIRST_NAME = E3.FIRST_NAME,
           E2.LAST_NAME = E3.LAST_NAME
WHEN NOT MATCHED THEN
   INSERT (E2.EMPLOYEE_ID, E2.FIRST_NAME, E2.LAST_NAME, E2.EMAIL, E2.PHONE_NUMBER, E2.HIRE_DATE, E2.JOB_ID, E2.SALARY, E2.COMMISSION_PCT, E2.MANAGER_ID, E2.DEPARTMENT_ID) 
   VALUES (E3.EMPLOYEE_ID, E3.FIRST_NAME, E3.LAST_NAME, E3.EMAIL, E3.PHONE_NUMBER, E3.HIRE_DATE, E3.JOB_ID, E3.SALARY, E3.COMMISSION_PCT, E3.MANAGER_ID, E3.DEPARTMENT_ID);