/* b) Crie no schema do usuario RH 2 tabelas:
        A primeira tabela com o nome EMPREGADOS devera ser um clone de estrutura (incluindo constraints) e dados da tabela HR.EMPLOYEES;
        A segunda tabela com o nome DEPARTAMENTOS devera ser um clone de estrutura (incluindo constraints) e dados da tabela HR.DEPARTMENTS;
*/

GRANT SELECT ON hr.employees TO rh;
GRANT SELECT ON hr.departments TO rh;

CREATE TABLE RH.EMPREGADOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE RH.DEPARTAMENTOS AS SELECT * FROM HR.DEPARTMENTS;

ALTER TABLE RH.EMPREGADOS ADD CONSTRAINT "EMP_SALARY_MIN" CHECK (salary > 0) ENABLE;
ALTER TABLE RH.EMPREGADOS ADD CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL") ENABLE;
ALTER TABLE RH.EMPREGADOS ADD CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID") ENABLE;
ALTER TABLE RH.EMPREGADOS ADD CONSTRAINT "EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "RH"."EMPREGADOS" ("EMPLOYEE_ID") ENABLE;

ALTER TABLE RH.DEPARTAMENTOS ADD CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID") ENABLE;
ALTER TABLE RH.EMPREGADOS ADD CONSTRAINT "EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "RH"."DEPARTAMENTOS" ("DEPARTMENT_ID") ENABLE;
ALTER TABLE RH.DEPARTAMENTOS ADD CONSTRAINT "DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "RH"."EMPREGADOS" ("EMPLOYEE_ID") ENABLE;